services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: formulario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  api:
    build: ./backend
    env_file: .env
    depends_on: [db]
    ports: ["8000:8000"]

  web:
    build: ./frontend
    depends_on: [api]
    ports: ["3000:3000"]
volumes:
  dbdata:
