ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS numero_radicacion TEXT;

ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS fecha_radicacion DATE;

ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS bpin TEXT;

ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS soportes_folios INT NOT NULL DEFAULT 0;

ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS soportes_planos INT NOT NULL DEFAULT 0;

ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS soportes_cds INT NOT NULL DEFAULT 0;

ALTER TABLE formulario
    ADD COLUMN IF NOT EXISTS soportes_otros INT NOT NULL DEFAULT 0;
