from Backend.utils.database import Base
from .dependencia import Dependencia
from .linea_estrategica import LineaEstrategica
from .programa import Programa
from .sector import Sector
from .meta import Meta
from .formulario import Formulario
from .metas import Metas
from .variable import Variable
from .variables import Variables
from .politica import Politica
from .politicas import Politicas
from .categoria import Categoria
from .categorias import Categorias
from .subcategoria import Subcategoria
from .subcategorias import Subcategorias
