from Backend.utils.database import Base
from .dependencia import Dependencia
from .linea_estrategica import LineaEstrategica
from .programa import Programa
from .sector import Sector
from .meta import Meta
from .formulario import Formulario
from .metas import Metas
from .variable_sectorial import VariableSectorial
from .variables_sectorial import VariablesSectorial
from .variable_tecnico import VariableTecnico 
from .variables_tecnico import VariablesTecnico 
from .politica import Politica
from .politicas import Politicas
from .categoria import Categoria
from .categorias import Categorias
from .subcategoria import Subcategoria
from .subcategorias import Subcategorias
from .estructura_financiera import EstructuraFinanciera
from .viabilidad import Viabilidad
from .viabilidades import Viabilidades
from .tipo_viabilidad import TipoViabilidad
from .funcionario_viabilidad import FuncionarioViabilidad